openapi: 3.0.0
info:
  title: Video API
  description: An API for managing videos and events
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
paths:
  /videos:
    post:
      summary: Create a new video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoDto'
      responses:
        '201':
          description: Video created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateVideoResponseDto'
  /videos/{videoId}:
    get:
      summary: Get a video by ID
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Video found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoResponseDto'
        '404':
          description: Video not found
  /events:
    get:
      summary: Get events
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDto'
components:
  schemas:
    VideoDto:
      type: object
      properties:
        url:
          type: string
        user:
          type: string
    VideoResponseDto:
      type: object
      properties:
        id:
          type: string
    CreateVideoResponseDto:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/VideoResponseDto'
    EventDto:
      type: object
      properties:
        id:
          type: string
